# 19_run_frontier.R — primeira especificacao da fronteira (Background Job).
raiz <- if (file.exists("project.Rproj")) getwd() else dirname(getwd()); setwd(raiz)
source("R/00_setup.R"); source("R/01_config.R"); source("R/15_event_study.R"); source("R/13_efficiency_frontier.R")
con <- dbConnect(duckdb(), caminho("data","processed","observatory.duckdb"), read_only = TRUE)
p <- montar_painel_sfa(con, COORTES_PSP); dbDisconnect(con, shutdown = TRUE)
sink(caminho("outputs","models","sfa_exploratorio.txt"), split = TRUE)
cat("FRONTEIRA ESTOCASTICA EXPLORATORIA —", format(Sys.time()), "\n")
cat("painel porto-ano:", nrow(p), "obs |", uniqueN(p$cdtup), "portos |", sum(p$publico == 1 & !duplicated(p$cdtup)), "publicos\n\n")
m <- estimar_sfa(p)
cat("=== Cobb-Douglas (BC95, ineficiencia com determinantes) ===\n"); print(summary(m$cd))
cat("\n=== Translog ===\n"); print(summary(m$tl))
cat("\n=== frontier::sfa BC95 (Cobb-Douglas) ===\n"); print(summary(m$bc))
lr <- 2 * (m$tl$mlLoglik - m$cd$mlLoglik)
cat(sprintf("\nLR translog vs Cobb-Douglas: %.2f (gl = 3, p = %.4f)\n", lr, pchisq(lr, 3, lower.tail = FALSE)))
ef <- as.data.table(efficiencies(m$tl)); ef <- cbind(as.data.table(m$dados)[, .(cdtup, porto, tipo_autoridade, ano, psp)], ef)
cat("\nEficiencia tecnica media (translog, BC):\n")
print(ef[, .(te_media = round(mean(teBC), 3), n = .N), by = .(tipo_autoridade, psp)])
fwrite(ef, caminho("outputs","models","sfa_efficiencies.csv"))
saveRDS(m, caminho("outputs","models","sfa_models.rds"))
for (nm in c("cd","tl")) { ct <- coef(summary(m[[nm]])); fwrite(data.table(modelo = nm, termo = rownames(ct), ct), caminho("outputs","models", sprintf("sfa_portoano_%s_coefs.csv", nm))) }
sink(); cat("concluido\n")
